### ISSUE TITLE
vibrating transactions

### ISSUE THREAD

**Issue by rsnel** [themoritz/txgraph#9]
Hi, 

I like this project very much and I built it successfully. It is a beautiful way of displaying transactions and I would like to use it for my multi-wallet-viewer (basically it take a bunch of addresses and bunch of xpub's and then you can step through it etc) but I have a problem with vibrating transactions (that do not come to rest).

For example with a transaction that creates 8 outputs and another transaction that reconciles them. The solution is to (temporarily) delete an anchor or try to grab it (very difficult). Perhaps it is possible to add some (more) dampening in the layout algorithm. If it is difficult to reproduce, I will try to  find one.

Greetings,

Rik.

**Comment by themoritz** [comment]
Hi Rik, I'm aware of the issue that happens when two transactions are connected by a lot of UTXOs.

The reason is that the attraction force that pull two transactions together is applied for each edge between them. So with many edges the force becomes too large and then doesn't find a balance with the repulsion force between the transactions.

One solution that I thought of is to divide the attraction force by how many edges exist between the transactions. That way, the total force will always be roughly similar to the case where only one edge exists. I hope that makes sense. I can put together a PR if I find time after the holidays.

Is your multi-wallet-viewer available somewhere?

**Comment by themoritz** [comment]
Ok I ended up implementing this right away. Let me know in case this is still an issue.

**Comment by rsnel** [comment]
Thanks, it works!

I want to clean up the code of the  multi-wallet-viewer a little bit, and then I will put it up on github,  I will notifiy you in this thread.
